// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// inspectDB
List inspectDB(CharacterVector& dbpath);
RcppExport SEXP xapianExamples_inspectDB(SEXP dbpathSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< CharacterVector& >::type dbpath(dbpathSEXP );
        List __result = inspectDB(dbpath);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// index
void index(CharacterVector& dbpath, CharacterVector& datapath, NumericVector& idField, List& indexFields, CharacterVector& stemmer);
RcppExport SEXP xapianExamples_index(SEXP dbpathSEXP, SEXP datapathSEXP, SEXP idFieldSEXP, SEXP indexFieldsSEXP, SEXP stemmerSEXP) {
BEGIN_RCPP
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< CharacterVector& >::type dbpath(dbpathSEXP );
        Rcpp::traits::input_parameter< CharacterVector& >::type datapath(datapathSEXP );
        Rcpp::traits::input_parameter< NumericVector& >::type idField(idFieldSEXP );
        Rcpp::traits::input_parameter< List& >::type indexFields(indexFieldsSEXP );
        Rcpp::traits::input_parameter< CharacterVector& >::type stemmer(stemmerSEXP );
        index(dbpath, datapath, idField, indexFields, stemmer);
    }
    return R_NilValue;
END_RCPP
}

