# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

inspectDB <- function(dbpath) {
    .Call('xapianExamples_inspectDB', PACKAGE = 'xapianExamples', dbpath)
}

index <- function(dbpath, datapath, idField, indexFields, stemmer) {
    invisible(.Call('xapianExamples_index', PACKAGE = 'xapianExamples', dbpath, datapath, idField, indexFields, stemmer))
}

rcpp_hello_world <- function() {
    .Call('xapianExamples_rcpp_hello_world', PACKAGE = 'xapianExamples')
}

